//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AscentrikProjectWorkflow.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.ProjectAssignments = new HashSet<ProjectAssignment>();
            this.ProjectCostings = new HashSet<ProjectCosting>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int ListId { get; set; }
        public int Priority { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectBrief { get; set; }
        public string LinkdinLink { get; set; }
        public string Requester { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<bool> DatesInformedToClient { get; set; }
        public Nullable<int> NumberOfCompaniesApproved { get; set; }
        public Nullable<int> JobTitlesPerCompany { get; set; }
        public Nullable<int> RecordsToBeResearched { get; set; }
        public Nullable<int> DuplicateFounds { get; set; }
        public Nullable<int> NoOfRecordsDeliverd { get; set; }
        public Nullable<System.DateTime> ExpectedDeliveryDate { get; set; }
        public Nullable<System.DateTime> ActualDeliveryDate { get; set; }
        public Nullable<System.DateTime> FTPUploadDate { get; set; }
        public string FTPUploadRemarks { get; set; }
        public int ProjectStatus { get; set; }
        public string AllotedTo { get; set; }
        public string Names { get; set; }
        public string ResearchRemark { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> EditedBy { get; set; }
        public Nullable<System.DateTime> EditedOn { get; set; }
        public bool IsActive { get; set; }
    
        public virtual List List { get; set; }
        public virtual Priority Priority1 { get; set; }
        public virtual ProjectStatu ProjectStatu { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<ProjectAssignment> ProjectAssignments { get; set; }
        public virtual ICollection<ProjectCosting> ProjectCostings { get; set; }
    }
}
