//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AscentrikProjectWorkflow.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectCosting
    {
        public int Id { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<decimal> CostPerRecord { get; set; }
        public Nullable<decimal> ProjectInvoice { get; set; }
        public Nullable<int> Currency { get; set; }
        public string InvoiceCode { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<int> PaymentStatus { get; set; }
        public string InvoiceRemark { get; set; }
        public Nullable<int> EditedBy { get; set; }
        public Nullable<System.DateTime> EditedOn { get; set; }
    
        public virtual Currency Currency1 { get; set; }
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
    }
}
