//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AscentrikProjectWorkflow.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Clients = new HashSet<Client>();
            this.Clients1 = new HashSet<Client>();
            this.Lists = new HashSet<List>();
            this.Lists1 = new HashSet<List>();
            this.ListTypes = new HashSet<ListType>();
            this.ListTypes1 = new HashSet<ListType>();
            this.Projects = new HashSet<Project>();
            this.Projects1 = new HashSet<Project>();
            this.ProjectAssignments = new HashSet<ProjectAssignment>();
            this.ProjectCostings = new HashSet<ProjectCosting>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
        }
    
        public int Id { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public string DisplayName { get; set; }
        public int Role { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Client> Clients { get; set; }
        public virtual ICollection<Client> Clients1 { get; set; }
        public virtual ICollection<List> Lists { get; set; }
        public virtual ICollection<List> Lists1 { get; set; }
        public virtual ICollection<ListType> ListTypes { get; set; }
        public virtual ICollection<ListType> ListTypes1 { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<Project> Projects1 { get; set; }
        public virtual ICollection<ProjectAssignment> ProjectAssignments { get; set; }
        public virtual ICollection<ProjectCosting> ProjectCostings { get; set; }
        public virtual Role Role1 { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
    }
}
